config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    # api = Prismic.api('https://blogprismicdz.cdn.prismic.io/api/v2')
    # response = api.query(Prismic::Predicates.at("document.type", "page"))
    # documents = response.results
    response = Faraday.get('https://blogprismicdz.cdn.prismic.io/api/v2/documents/search?ref=ZG90TxAAACUAE5Mc')    
    @results = JSON.parse(response.body)['results']
  end

  # GET /posts/1 or /posts/1.json
  def show
    response = Faraday.get('https://blogprismicdz.cdn.prismic.io/api/v2/documents/search?ref=ZG90TxAAACUAE5Mc&q=%5B%5B%3Ad+%3D+at%28document.id%2C+%22' + params[:id] + '%22%29+%5D%5D')    
    @post = JSON.parse(response.body)['results'][0]
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.first
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogprismic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post['data']['title'][0]['text'] %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post['data']['content'][0]['text'] %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  
  <% @results.each do |post| %>
    <% if post['type'] == 'post'%>
      <div class="card" style="width: 18rem;">    
        <div class="card-body">
          <h5 class="card-title"><%= post['data']['title'][0]['text']%></h5>
          <p class="card-text">

            <b>Document Type:</b><%= post['type']%><br>
            <b>Document Id:</b> <%= post['id']%>
          </p>
          <a href="/posts/<%= post['id'] %>" class="btn btn-primary">Show Post</a>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 80%; margin: 0 auto;">    
  <div class="card-body">
    <h5 class="card-title"><%= @post['data']['title'][0]['text'] %></h5>
    <p class="card-text">
      <%= @post['data']['content'][0]['text'] %>
    </p> 
  </div>
  <%= link_to "Back to posts", {controller: "posts", action: "index"}, class: "btn btn-primary" %>
</div>

</div>